// Generated by CoffeeScript 1.9.3
$().ready(function() {
  $('#volume').val($.cookie('volume') != null ? $.cookie('volume') : 0.1);
  $('#volume').on('change', function() {
    var vol;
    vol = $(this).val();
    $.cookie('volume', vol, {
      expires: 100 * 365
    });
    return window.mysound.setVolume(vol);
  });
  $('#volumeForm').on({
    mouseenter: function() {
      return $(this).fadeTo(500, 1);
    },
    mouseleave: function() {
      return $(this).fadeTo(1000, 0.01);
    }
  });
  $('#play').on('click', function() {
    $('#playForm').addClass('noDisplay');
    return window.mysound = new MySound();
  });
  return window.onerror = function(e) {
    return alert(e);
  };
});
