// Generated by CoffeeScript 1.10.0
window.BASE_TIME = false;

window.TIME_JSON = [];

$().ready(function() {
  $('#clear').on('click', function() {
    window.BASE_TIME = false;
    window.TIME_JSON = [];
    return $('textarea').html('');
  });
  return $(window).on('keydown', function(e) {
    var now, record;
    if (e.keyCode !== 32) {
      return;
    }
    now = +new Date();
    record = 0;
    if (window.BASE_TIME === false) {
      window.BASE_TIME = now;
    } else {
      record = now - window.BASE_TIME;
    }
    window.TIME_JSON.push(record);
    return $('textarea').html(JSON.stringify(window.TIME_JSON, null, 2));
  });
});
